# *********************************************
# Authors: Aurore Archimbaud 
#          TBS Business School
# *********************************************



# Packages ----------------------------------------------------------------
# libraries
# For ICS
library(ICS)

# For data
library(MaxSkew)

# For preprocessing
library(stringr)

# For plot
library(ggplot2)
library(patchwork)


# function for parsing axis labels
parse_labels <- function(labels, ...) parse(text = labels, ...)



# Import data -------------------------------------------------------------
data("OLYMPIC_DECATHLON_2016")
df <- data.frame(OLYMPIC_DECATHLON_2016)

# create name variable
df <- cbind(name = paste(df$OS, unlist(lapply(str_extract_all(df$ATHLETE, "[A-Z]{2,}"),
                                              function(x) paste(x, collapse = " "))), sep = "_"),
            df[,-c(1:3)])
decathlon_data <- df[,-1]

# parameters for plots
# we show the names of the two best and worst athletes as well as TAIWO
keep_athletes <- c("1_EATON", "2_MAYER", "11_TAIWO", "22_NAKAMURA", "23_SALURI")
df$group <- as.factor(df$name)
colors_plot <- rep("lightgrey",nrow(df))
colors_plot[df$name %in% keep_athletes] <- c("aquamarine3", "cyan3", "coral2",
                                             "deeppink3", "darkmagenta")
names(colors_plot) <- df$name
order_var <- c("X100.METRES",  "X400.METRES", "X1500.METRES", "X110.METRES.HURDLES",
               "LONG.JUMP","HIGH.JUMP",  "POLE.VAULT","SHOT.PUT",
               "DISCUS.THROW",  "JAVELIN.THROW")


# ICS with Cov-Cov4 -------------------------------------------------------

## Initial data ------------------------------------------------------------
res <- ICS(df[,order_var])
df_ics <- data.frame(name = df$name, group = colors_plot, res$scores)

p1 <- df_ics %>% ggplot(aes(x=IC.1, y = IC.2, color = name)) +
  geom_point() +
  geom_text(data = df_ics[df_ics$name %in% keep_athletes,], aes(label = name),
            vjust = 0, nudge_y = 0.1, nudge_x = -0.1, size = 2) +
  scale_color_manual("athletes", values = colors_plot) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(x = parse_labels("IC[1]"), y = parse_labels("IC[2]"))

p2 <- df_ics %>% ggplot(aes(x=IC.1, y = IC.3, color = name)) +
  geom_point() +
  geom_text(data = df_ics[df_ics$name %in% keep_athletes,], aes(label = name),
            vjust = 0, nudge_y = 0.1, nudge_x = -0.1, size = 2) +
  scale_color_manual("athletes", values = colors_plot) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(x = parse_labels("IC[1]"), y = parse_labels("IC[3]"))


p3 <- df_ics %>% ggplot(aes(x=IC.1, y = IC.10, color = name)) +
  geom_point() +
  geom_text(data = df_ics[df_ics$name %in% keep_athletes,], aes(label = name),
            vjust = 0, nudge_y = 0.1, nudge_x = -0.1, size = 2) +
  scale_color_manual("athletes", values = colors_plot) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(x = parse_labels("IC[1]"), y = parse_labels("IC[10]"))

pdf("R/figures/application/decathlon_Rio_2016_ICS_initial.pdf", width = 12, height = 3)
p1+p2+p3 +
  plot_annotation(
    title = 'Decathlon data',
    theme = theme(plot.title = element_text(hjust = 0.5))
  )
dev.off()

## Data with 1 additional athlete ------------------------------------------------------------
# We generate one additional athlete to the data set based on the on the behavior of SALURI:  
# initial values plus a value generated by a uniform between -20 and 20.

# seed
set.seed(20241016)

# data generation
df_ini <- df[df$name=="23_SALURI",]
df_new <- data.frame(name = paste(df_ini$name, 1),
                     df_ini[,order_var]+sapply(order_var, function(i) runif(1,-20,20)),
                     group = paste(df_ini$name, 1))
df_modified <- rbind(df, df_new)

# ICS
res <- ICS(df_modified[,order_var])
df_ics <- data.frame(name = df_modified$name,  res$scores)
keep_athletes <- c(keep_athletes,  "23_SALURI 1")
colors_plot <- c(colors_plot, "23_SALURI 1" = "darkmagenta")

# Plot
p1 <- df_ics %>% ggplot(aes(x=IC.1, y = IC.2, color = name)) +
  geom_point() +
  geom_text(data = df_ics[df_ics$name %in% keep_athletes,], aes(label = name),
            vjust = 0, nudge_y = 0.1, nudge_x = -0.1, size = 2) +
  scale_color_manual("athletes", values = colors_plot) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(x = parse_labels("IC[1]"), y = parse_labels("IC[2]"))

p2 <- df_ics %>% ggplot(aes(x=IC.1, y = IC.3, color = name)) +
  geom_point() +
  geom_text(data = df_ics[df_ics$name %in% keep_athletes,], aes(label = name),
            vjust = 0, nudge_y = 0.1, nudge_x = -0.1, size = 2) +
  scale_color_manual("athletes", values = colors_plot) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(x = parse_labels("IC[1]"), y = parse_labels("IC[3]"))


p3 <- df_ics %>% ggplot(aes(x=IC.1, y = IC.10, color = name)) +
  geom_point() +
  geom_text(data = df_ics[df_ics$name %in% keep_athletes,], aes(label = name),
            vjust = 0, nudge_y = 0.1, nudge_x = -0.1, size = 2) +
  scale_color_manual("athletes", values = colors_plot) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(x = parse_labels("IC[1]"), y = parse_labels("IC[10]"))

pdf("figures/application/decathlon_Rio_2016_ICS_one_athlete.pdf", width = 12, height = 3)
p1+p2+p3 +
  plot_annotation(
    title = 'Decathlon data with one additional athlete',
    theme = theme(plot.title = element_text(hjust = 0.5))
  )
dev.off()


## Data with 2 additional athletes ------------------------------------------------------------
# We generate one additional athlete to the data set.

# data generation
df_new <- data.frame(name = paste(df_ini$name, 2),
                     df_ini[,order_var]+sapply(order_var, function(i) runif(1,-20,20)),
                     group = paste(df_ini$name, 2))
df_modified <- rbind(df_modified, df_new)

# ICS
res <- ICS(df_modified[,order_var])
df_ics <- data.frame(name = df_modified$name,  res$scores)
keep_athletes <- c(keep_athletes, "23_SALURI 2" )
colors_plot <- c(colors_plot, "23_SALURI 2" = "darkmagenta")

# Plot
p1 <- df_ics %>% ggplot(aes(x=IC.1, y = IC.2, color = name)) +
  geom_point() +
  geom_text(data = df_ics[df_ics$name %in% keep_athletes,], aes(label = name),
            vjust = 0, nudge_y = 0.1, nudge_x = -0.1, size = 2) +
  scale_color_manual("athletes", values = colors_plot) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(x = parse_labels("IC[1]"), y = parse_labels("IC[2]"))

p2 <- df_ics %>% ggplot(aes(x=IC.1, y = IC.3, color = name)) +
  geom_point() +
  geom_text(data = df_ics[df_ics$name %in% keep_athletes,], aes(label = name),
            vjust = 0, nudge_y = 0.1, nudge_x = -0.1, size = 2) +
  scale_color_manual("athletes", values = colors_plot) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(x = parse_labels("IC[1]"), y = parse_labels("IC[3]"))


p3 <- df_ics %>% ggplot(aes(x=IC.1, y = IC.10, color = name)) +
  geom_point() +
  geom_text(data = df_ics[df_ics$name %in% keep_athletes,], aes(label = name),
            vjust = 0, nudge_y = 0.1, nudge_x = -0.1, size = 2) +
  scale_color_manual("athletes", values = colors_plot) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(x = parse_labels("IC[1]"), y = parse_labels("IC[10]"))

pdf("figures/application/decathlon_Rio_2016_ICS_two_athletes.pdf", width = 12, height = 3)
p1+p2+p3 +
  plot_annotation(
    title = 'Decathlon data with two additional athletes',
    theme = theme(plot.title = element_text(hjust = 0.5))
  )
dev.off()
